name: FreeFireworks
version: 1.1.0
main: io.github.AKtomik.freeFireworks.FreeFireworks
api-version: 1.21

commands:
  firework:
    description: Fire some fireworks
    usage: /<command> [effect] [color] [fade]
    aliases:
      - lanch
      - fireme
      - pfiou
    permission: freefireworks.launch.self

  fireplayer:
    description: Fire some fireworks at player
    usage: /<command> <player> [effect] [color] [fade]
    permission: freefireworks.launch.others

permissions:
  freefireworks.launch.self:
    description: Allow launching some fireworks at yourself
    default: true
  freefireworks.launch.others:
    description: Allow launching some fireworks at others
    default: op

